export DEFAULTS_JOURNAL_PERSONAL="$DEFAULTS_MYDOCS/journal/pessoal.txt"
export DEFAULTS_JOURNAL_WORK="$DEFAULTS_MYDOCS/journal/work.txt"
export DEFAULTS_JOURNAL_TEMPLATE="$DEFAULTS_PREFERENCES/jrnl/jrnl.yaml"