source "$DEFAULTS_APPS/git-manager.sh"
source "$DEFAULTS_APPS/7-zip.sh"
source "$DEFAULTS_APPS/browser.sh"
source "$DEFAULTS_APPS/editors.sh"
source "$DEFAULTS_APPS/windows-terminal.sh"
source "$DEFAULTS_APPS/image-tools.sh"
